name: Nix build

on:
  [push, pull_request]

jobs:
  flake-default:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build flake
      run: nix build -L #.
